name: MediaDownloader4Windows

on: push

env:
  QT_VERSION:     "5.15.2"
  MINGW_VERSION:  "win32_mingw81"
  MINGW_PATH:     "mingw810_32"
  BUILD_TYPE:      Release

jobs:
  build:
    runs-on: windows-latest
    steps:
    -
      uses: actions/checkout@v2
#    -
#      name: Check mingw g++ version
#      run: |
#        Write-Output (Get-Command g++.exe).Path
#        g++.exe --version
    -
      name: Install correct version of mingw
      uses: crazy-max/ghaction-chocolatey@v1
      with:
        args: install mingw --version=8.1.0  -y
    -
      name: update env
      run: |
        echo "C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
    -
      name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: ${{ env.QT_VERSION }}
        arch: ${{ env.MINGW_VERSION }}
        dir: "${{github.workspace}}/qt"
        install-deps: "true"
        host: 'windows'
        target: 'desktop'
        archives: 'qtbase qtwidgets qtcore qtnetwork'
        cache: 'false'
        cache-key-prefix: 'install-qt-action'
        setup-python: 'true'
        set-env: 'true'
        tools-only: 'false'
        aqtversion: '==3.1.*'
        py7zrversion: '==0.20.*'
        extra: '--external 7z'
    -
      name: Configure CMake
      working-directory: ${{github.workspace}}
      env:
        CMAKE_PREFIX_PATH: ${{env.Qt5_Dir}}

      run: cmake  -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -G "CodeBlocks - MinGW Makefiles" -B ${{github.workspace}}/build
    -
      name: Build Project
      working-directory: ${{github.workspace}}/build
      run: |
        mingw32-make.exe VERBOSE=1
